### ISSUE TITLE
Backend not starting

### ISSUE THREAD

**Issue by olegasdo** [tiangolo/full-stack-fastapi-postgresql#41]
Hello
I've tried running project locally on Windows server (using cookiecutter), but backend is not starting.
docker logs shows:
Checking for script in /app/prestart.sh
Running script /app/prestart.sh
: not foundad.sh: 2: /app/prestart.sh:

**Comment by olegasdo** [comment]
Sorry, was using docker logs
"docker-compose logs backend" shows all the texts :)
Attaching to test_project_backend_1
backend_1        | Checking for script in /app/prestart.sh
backend_1        | Running script /app/prestart.sh
: not found      | /start-reload.sh: 2: /app/prestart.sh:

**Comment by olegasdo** [comment]
there was an issue with  backend/app/prestart.sh
when executing directly in container it returned error "/usr/bin/env: ‘bash\r’: No such file or directory"
changing line endings in vscode from "CRLF" to "LF" solved the issue. Project files might need update

**Comment by mastacheata** [comment]
I think that's an issue on cookiecutter and not on the files in this repository.

**Comment by tiangolo** [comment]
Indeed, it's probably an issue with Cookiecutter on Windows: https://github.com/cookiecutter/cookiecutter/pull/1159

But still, this should be fixed now with https://github.com/tiangolo/full-stack-fastapi-postgresql/pull/149 🎉 

It fixes the line endings of shell scripts right after generation.

**Comment by rohitkumar93** [comment]
I changed my prestart.sh to "LF" using VScode too, and checked it as well. 
But I am getting the same error:
`Checking for script in /app/prestart.sh

Running script /app/prestart.sh

/start-reload.sh: 22: .: Can't open /app/prestart.sh`

**Comment by pranjalsrv** [comment]
This is in the output of command `docker-compose logs`:

`backend_1  | Checking for script in /app/prestart.sh
backend_1  | There is no script /app/prestart.sh
backend_1  | INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
backend_1  | INFO:     Started reloader process [1] using statreload
backend_1  | ERROR:    Error loading ASGI app. Import string ":app" must be in format "<module>:<attribute>".`

This issue still persists on running on Windows. It is the duplicate of 
I tried changing the line endings using both VSCode and manually using the command:`find . -type f -exec dos2unix {} \;`, but the issue still exists.

**Comment by pranjalsrv** [comment]
This is in the output of command `docker-compose logs`:

```backend_1  | Checking for script in /app/prestart.sh
backend_1  | There is no script /app/prestart.sh
backend_1  | INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
backend_1  | INFO:     Started reloader process [1] using statreload
backend_1  | ERROR:    Error loading ASGI app. Import string ":app" must be in format "<module>:<attribute>".```

This issue still persists on running on Windows. It is the duplicate of 
I tried changing the line endings using both VSCode and manually using the command:`find . -type f -exec dos2unix {} \;`, but the issue still exists.

**Comment by pranjalsrv** [comment]
This is in the output of command `docker-compose logs`:

```backend_1  | Checking for script in /app/prestart.sh
backend_1  | There is no script /app/prestart.sh
backend_1  | INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
backend_1  | INFO:     Started reloader process [1] using statreload
backend_1  | ERROR:    Error loading ASGI app. Import string ":app" must be in format "<module>:<attribute>".
```

This issue still persists on running on Windows. It is the duplicate of 
I tried changing the line endings using both VSCode and manually using the command:`find . -type f -exec dos2unix {} \;`, but the issue still exists.

**Comment by pranjalsrv** [comment]
This is in the output of command `docker-compose logs`:

```backend_1  | Checking for script in /app/prestart.sh
backend_1  | There is no script /app/prestart.sh
backend_1  | INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
backend_1  | INFO:     Started reloader process [1] using statreload
backend_1  | ERROR:    Error loading ASGI app. Import string ":app" must be in format "<module>:<attribute>".
```

This issue still persists on running on Windows.
I tried changing the line endings using both VSCode and then manually by using the command: `find . -type f -exec dos2unix {} \;`, but the issue still exists.

**Comment by danielbf92** [comment]
@pranjalsrv did you manage to solve the problem? Right now it sends me that error.

```
Checking for script in /app/prestart.sh
There is no script /app/prestart.sh
INFO:     Uvicorn running on http://0.0.0.0:80 (Press CTRL+C to quit)
INFO:     Started reloader process [1] using statreload
ERROR:    Error loading ASGI app. Import string ":app" must be in format "<module>:<attribute>".
```

**Comment by OddBlueDog** [comment]
Have the same issue on macOS I have put the line endings as LF. Any ideas?

**Comment by alemengana** [comment]
> there was an issue with backend/app/prestart.sh
> when executing directly in container it returned error "/usr/bin/env: ‘bash\r’: No such file or directory"
> changing line endings in vscode from "CRLF" to "LF" solved the issue. Project files might need update

Thanks my friend !!!!!!

**Comment by badr-elmazaz** [comment]
I changed the end of line sequence from CRLF to LF end it worked. I used visual studio code to change this
